name: usctbench
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - h5py
  - pydantic
  - pyyaml
  - matplotlib
  - scikit-image
  - pandas
  - pytest
  - ruff
  - black
  - pillow
  - pip:
      - -e .[dev,viz]
