"""Helpers for explicitly labelled ToF diagnostics, not reconstruction algorithms."""

from __future__ import annotations

import numpy as np

from usctbench.core.schema import MeasurementSpec
from usctbench.operators.eikonal import EikonalForward, fast_march


def diagnostic_case(case, delays_s, label):
    """Replace only the observable, preserving acquisition weights and geometry.

    Matched controls are GT-generated by the caller. They must never inherit a
    k-Wave provenance label. Original arrays are not mutated; no ROI is inferred.
    """
    if label not in {"matched_straight", "matched_eikonal", "kwave"}:
        raise ValueError("unknown diagnostic label")
    original = case.measurement
    if original.delta_tof_s is None:
        raise ValueError("an original differential-ToF acquisition is required")
    shape = (len(case.geometry.tx_pos_m), len(case.geometry.rx_pos_m))
    values = np.asarray(delays_s)
    if values.shape != shape or np.iscomplexobj(values):
        raise ValueError("delays must be a real (tx,rx) array")
    mask = np.isfinite(original.delta_tof_s)
    if original.valid_mask is not None:
        mask &= original.valid_mask
    if not np.isfinite(values[mask]).all():
        raise ValueError("control has nonfinite values on original active channels")
    if label == "kwave" and not np.array_equal(
        values[mask], original.delta_tof_s[mask]
    ):
        raise ValueError("a k-Wave-labelled control cannot replace observed delays")
    if case.grid.roi_mask is not None:
        raise ValueError("this audit requires no inversion ROI")
    measurement = MeasurementSpec(
        domain="features",
        delta_tof_s=np.where(mask, values, np.nan),
        valid_mask=mask,
        ray_weights=original.ray_weights,
        feature_quality=original.feature_quality,
    )
    meta = {
        **case.metadata,
        "diagnostic_control": label,
        "diagnostic_not_real_data_benchmark": label != "kwave",
        "parent_measurement_provenance": case.metadata.get("measurement_provenance"),
        "weights_policy": "original acquisition weights retained, not estimated control noise",
        "uses_gt_generated_measurement": True,
    }
    if label != "kwave":
        meta.update(
            measurement_provenance="oracle_travel_time",
            forward_model="diagnostic_" + label,
            benchmark_type="matched_model_diagnostic",
            feature_source=label,
            ground_truth_used_for_measurement=True,
            uses_kwave_wavefield=False,
            uses_complex_wavefield=False,
            water_reference_used=False,
            inverse_crime_risk="same_discrete_operator_diagnostic",
        )
    return case.model_copy(update={"measurement": measurement, "metadata": meta})


def streamed_eikonal_delta(grid, geometry, speed, c0=1500.0):
    """Same discrete differential Eikonal map, one source tape at a time.

    For forward-only diagnostics, retaining every Jacobian tape is unnecessary.
    This performs exactly 2*n_tx source solves. It does not return a Jacobian,
    perform a reconstruction, access GT, or claim a higher-order discretization.
    """
    speed = np.asarray(speed, dtype=float)
    if speed.shape != grid.shape or not np.isfinite(speed).all() or np.any(speed <= 0):
        raise ValueError("speed must be finite, positive and match the grid")
    op = EikonalForward(grid, geometry, background_speed_mps=c0)
    medium = op.extend(1 / speed, background=1 / c0)
    water = np.full(op.shape, 1 / c0)
    result = np.empty(op.ray_shape)
    for k, source in enumerate(op.source_coordinates):
        tape = fast_march(medium, grid.spacing_m, source)
        object_times = op.sample_receivers(tape.times)
        del tape
        tape = fast_march(water, grid.spacing_m, source)
        result[k] = object_times - op.sample_receivers(tape.times)
        del tape
    return result
